site:
  title: Space Cubics Documentation
  start_page: top::index.adoc

content:
  sources:
    - url: ./
      start_path: top
      branches: HEAD

    - url: ../sc-docs-a1
      branches: [HEAD]
      start_paths:
        - product/en
        - product/ja
        - software/en
        - software/ja
        - fpga/en
        - fpga/ja

asciidoc:
  attributes:
    stem: latexmath

ui:
  bundle:
    url: https://github.com/spacecubics/sc-docs-ui/releases/download/v1.4/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
